# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsrun < Formula
  desc "Easily run one-off tasks against an ECS Task Definition."
  homepage "https://github.com/masterpointio/ecsrun"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masterpointio/ecsrun/releases/download/v0.1.7/ecsrun_Darwin_arm64.tar.gz"
      sha256 "4a248c522272e8dff99cf5ee2926bd70b5d60f4d362316baaf9d3046fb510a36"

      def install
        bin.install "ecsrun"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masterpointio/ecsrun/releases/download/v0.1.7/ecsrun_Darwin_x86_64.tar.gz"
      sha256 "cbf192809c870085d5ca0c79cba1325fd9c6acf970bb95527cadd36dad5244bc"

      def install
        bin.install "ecsrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/masterpointio/ecsrun/releases/download/v0.1.7/ecsrun_Linux_x86_64.tar.gz"
      sha256 "c34d57ac113d6236e6c5d4a3c420fac4a9c54166ad430b1fbcefd6c5987938ff"

      def install
        bin.install "ecsrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masterpointio/ecsrun/releases/download/v0.1.7/ecsrun_Linux_arm64.tar.gz"
      sha256 "8814e94ce95423ac3f764f3f3521ca5f98c692551783d9ffd29c5ebca4b9d329"

      def install
        bin.install "ecsrun"
      end
    end
  end

  test do
    system "#{bin}/ecsrun --version"
  end
end
